-- Table: public.signup

-- DROP TABLE IF EXISTS public.signup;

CREATE TABLE IF NOT EXISTS public.signup
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2000 CACHE 1 ),
    shopname character varying COLLATE pg_catalog."default",
    lastname character varying COLLATE pg_catalog."default",
    licenceno integer,
    qualification character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    phoneno character varying COLLATE pg_catalog."default",
    drivinglicenceno integer,
    address character varying COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default",
    country character varying COLLATE pg_catalog."default",
    chemistlicence character varying COLLATE pg_catalog."default",
    drivinglicence character varying COLLATE pg_catalog."default",
    chemistphoto character varying COLLATE pg_catalog."default",
    firstname character varying COLLATE pg_catalog."default",
    dob character varying COLLATE pg_catalog."default",
    CONSTRAINT signup_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.signup
    OWNER to postgres;